services:
  laravel.test:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    platform: linux/amd64
    image: botble-cms-main-laravel.test
    user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "9000"  # Cho nginx truy cập PHP-FPM qua cổng 9000 (không cần map ra ngoài)
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      WWWGROUP: '${WWWGROUP:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    platform: linux/amd64
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - laravel.test
    networks:
      - sail

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - sail-mysql:/var/lib/mysql
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    platform: linux/amd64
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - sail-redis:/data
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '${FORWARD_PMA_PORT:-8080}:80'
    networks:
      - sail
    depends_on:
      - mysql

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
